package io.akka.openstatus.application;

import akka.Done;
import akka.javasdk.annotations.Component;
import akka.javasdk.eventsourcedentity.EventSourcedEntity;
import akka.javasdk.eventsourcedentity.EventSourcedEntityContext;
import io.akka.openstatus.domain.MonitorConfig;
import io.akka.openstatus.domain.MonitorEvent;
import io.akka.openstatus.domain.MonitorState;
import io.akka.openstatus.domain.ProbeStatus;
import java.time.Instant;

/**
 * One monitor — SPEC-001 §2-3. The entity id is the monitor id. All the decision-procedure
 * rules live in {@link MonitorState}, tested without a runtime in {@code MonitorStateTest};
 * this class decides only what to persist.
 */
@Component(id = "monitor")
public class MonitorEntity extends EventSourcedEntity<MonitorState, MonitorEvent> {

  private final String monitorId;

  public MonitorEntity(EventSourcedEntityContext context) {
    this.monitorId = context.entityId();
  }

  @Override
  public MonitorState emptyState() {
    return MonitorState.empty();
  }

  public Effect<Done> register(MonitorConfig config) {
    if (currentState().exists()) {
      return effects().error("monitor '" + monitorId + "' is already registered");
    }
    return effects()
        .persist(new MonitorEvent.MonitorRegistered(config))
        .thenReply(state -> Done.getInstance());
  }

  public record ProbeResult(String region, ProbeStatus status, Instant at) {}

  /**
   * The incident id, when a new one would be opened, is generated by the caller
   * ({@code monitorId + "-inc-" + at.toEpochMilli()}) rather than inside this pure-record
   * decision, so {@link MonitorState#onProbeResult} stays a pure function of its inputs.
   */
  public Effect<Done> recordProbeResult(ProbeResult result) {
    if (!currentState().exists()) {
      return effects().error("monitor '" + monitorId + "' is not registered");
    }
    var incidentId = monitorId + "-inc-" + result.at().toEpochMilli();
    var events = currentState().onProbeResult(result.region(), result.status(), result.at(), incidentId);
    return effects().persistAll(events).thenReply(state -> Done.getInstance());
  }

  public ReadOnlyEffect<MonitorState> get() {
    if (!currentState().exists()) {
      return effects().error("monitor '" + monitorId + "' is not registered");
    }
    return effects().reply(currentState());
  }

  @Override
  public MonitorState applyEvent(MonitorEvent event) {
    return currentState().apply(event);
  }
}
